name: zidni_mobile
description: "Zidni: The Context-First Super App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12_image: assets/splash.png
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
