name: zidni_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  http: ^1.2.0
  path_provider: ^2.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  provider: ^6.1.1
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  # Eyes dependencies (Gate EYES-1)
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  # Eyes dependencies (Gate EYES-2)
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
  
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
